version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: kapatid-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: 1120melvin
      POSTGRES_DB: kapatid_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localhost -d kapatid_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: